-- SQLite

INSERT INTO Cities (name, country)
VALUES
('Belfast','United Kingdom'),
('Enniskillen','United Kingdom'),
('Belfast','United Kingdom'),
('Londonderry','United Kingdom'),
('Birmingham','United Kingdom'),
('Coventry','United Kingdom'),
('Leicester','United Kingdom'),
('Golouchestershire','United Kingdom'),
('Halfpenny Green','United Kingdom'),
('Pailton','United Kingdom'),
('Turweston','United Kingdom'),
('Wellesbourne','United Kingdom'),
('Manchester','United Kingdom'),
('Woodfort','United Kingdom'),
('Chivenor','United Kingdom'),
('Newquai','United Kingdom'),
('Lyneham','United Kingdom'),
('Boscombe Down','United Kingdom'),
('Culdrose','United Kingdom'),
('St. Athan','United Kingdom'),
('Yeovilton','United Kingdom'),
('Haverfordwest','United Kingdom'),
('Cardiff','United Kingdom'),
('Swansea','United Kingdom'),
('Bristol','United Kingdom'),
('Liverpool','United Kingdom'),
('London','United Kingdom'),
('Plymouth','United Kingdom'),
('Bournemouth','United Kingdom'),
('Southampton','United Kingdom'),
('Lasham','United Kingdom'),
('Shoreham By Sea','United Kingdom'),
('Biggin Hill','United Kingdom'),
('London','United Kingdom'),
('London','United Kingdom'),
('Farnborough','United Kingdom'),
('Chalsgrove','United Kingdom'),
('Blackbushe','United Kingdom'),
('London','United Kingdom'),
('Southend','United Kingdom'),
('Lydd','United Kingdom'),
('Manston','United Kingdom'),
('Brough','United Kingdom'),
('Carlisle','United Kingdom'),
('Repton','United Kingdom'),
('Blackpool','United Kingdom'),
('Humberside','United Kingdom'),
('Barrow Island','United Kingdom'),
('Leeds','United Kingdom'),
('Warton','United Kingdom'),
('Hawarden','United Kingdom'),
('Newcastle','United Kingdom'),
('Teesside','United Kingdom'),
('East Midlands','United Kingdom'),
('Llanbedr','United Kingdom'),
('Ternhill','United Kingdom'),
('Shawbury','United Kingdom'),
('Woodvale','United Kingdom'),
('Kirkwall','United Kingdom'),
('Sumburgh','United Kingdom'),
('Wick','United Kingdom'),
('Aberdeen','United Kingdom'),
('Inverness','United Kingdom'),
('Glasgow','United Kingdom'),
('Edinburgh','United Kingdom'),
('Islay','United Kingdom'),
('Prestwick','United Kingdom'),
('Benbecula','United Kingdom'),
('Scatsta','United Kingdom'),
('Dundee','United Kingdom'),
('Stornoway','United Kingdom'),
('Tiree','United Kingdom'),
('Leuchars','United Kingdom'),
('Lossiemouth','United Kingdom'),
('Cambridge','United Kingdom'),
('Peterborough','United Kingdom'),
('Norwich','United Kingdom'),
('London','United Kingdom'),
('North Weald','United Kingdom'),
('Fowlmere','United Kingdom'),
('Cranfield','United Kingdom'),
('Exeter','United Kingdom'),
('Bristol','United Kingdom'),
('Oxford','United Kingdom'),
('Benson','United Kingdom'),
('Lakenheath','United Kingdom'),
('Mildenhall','United Kingdom'),
('Wattisham','United Kingdom'),
('Wyton','United Kingdom'),
('Fairford','United Kingdom'),
('Brize Norton','United Kingdom'),
('Odiham','United Kingdom'),
('Cosford','United Kingdom'),
('Northolt','United Kingdom'),
('Coningsby','United Kingdom'),
('Dishforth','United Kingdom'),
('Leeming','United Kingdom'),
('Church Fenton','United Kingdom'),
('Honington','United Kingdom'),
('Cottesmore','United Kingdom'),
('Scampton','United Kingdom'),
('Wittering','United Kingdom'),
('Linton-on-ouse','United Kingdom'),
('Waddington','United Kingdom'),
('Topcliffe','United Kingdom'),
('Cranwell','United Kingdom'),
('Barkston Heath','United Kingdom'),
('Marham','United Kingdom'),
('Cork','Ireland'),
('Galway','Ireland'),
('Dublin','Ireland'),
('Connaught','Ireland'),
('Kerry','Ireland'),
('Casement','Ireland'),
('Shannon','Ireland'),
('Sligo','Ireland'),
('Waterford','Ireland'),
('Nottingham','United Kingdom'),
('Campbeltown','United Kingdom'),
('Eday','United Kingdom'),
('Fair Isle','United Kingdom'),
('North Ronaldsay','United Kingdom'),
('Papa Westray','United Kingdom'),
('Stronsay','United Kingdom'),
('Sanday','United Kingdom'),
('Lerwick','United Kingdom'),
('Westray','United Kingdom'),
('Penzance','United Kingdom'),
('Angelsey','United Kingdom'),
('Barra','United Kingdom'),
('Dongloe','Ireland'),
('Leixlip','Ireland'),
('Outer Skerries','United Kingdom'),
('Inis Mor','Ireland'),
('Indreabhan','Ireland'),
('Unst','United Kingdom'),
('North Connel','United Kingdom'),
('Isle Of Wight','United Kingdom'),
('Lympne','United Kingdom'),
('Inisheer','Ireland'),
('Inishmaan','Ireland'),
('Colonsay','United Kingdom'),
('Tresco','United Kingdom'),
('London','United Kingdom'),
('Maidenhead','United Kingdom'),
('Wycombe','United Kingdom'),
('Bembridge','United Kingdom'),
('Shaftesbury','United Kingdom'),
('Glasgow','United Kingdom'),
('Forties Alpha','United Kingdom'),
('Perth','United Kingdom'),
('Caernarfon','United Kingdom'),
('Newcastle','Ireland'),
('Bantry','Ireland'),
('Duxford','United Kingdom'),
('Fairoaks','United Kingdom'),
('Rochester','United Kingdom'),
('Rothera Research Station','United Kingdom'),
('Beccles','United Kingdom'),
('Brawdy','United Kingdom'),
('Redhill','United Kingdom'),
('Enstone','United Kingdom'),
('Elstree','United Kingdom'),
('Sandtoft','United Kingdom'),
('Popham','United Kingdom'),
('Manchester','United Kingdom'),
('Shrewsbury','United Kingdom'),
('Burton-on-Trent','United Kingdom'),
('York','United Kingdom'),
('Leeds','United Kingdom'),
('Shobdon','United Kingdom'),
('Newtownards','United Kingdom'),
('Headcorn','United Kingdom'),
('Panshanger','United Kingdom'),
('Thurrock','United Kingdom'),
('Stapleford','United Kingdom'),
('Goodwood','United Kingdom'),
('Spadeadam','United Kingdom'),
('Kinloss','United Kingdom'),
('Mona','United Kingdom'),
('Longwood','United Kingdom');
